name: CI/CD Prod 🏓

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: zip, pdo_mysql, bcmath, exif, gettext, opcache, gd

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Build Docker Image
        run: docker build -t lynza-prod -f ./deploy/prod/Dockerfile .

      - name: Tag Docker Image
        run: docker tag lynza-prod registry.louisdev.fr/lynza-prod:latest

      - name: Log in to Registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin https://registry.louisdev.fr

      - name: Push to Registry
        run: docker push registry.louisdev.fr/lynza-prod:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          port: 22
          password: "${{ secrets.PROD_PASSWORD }}"
          script: "cd ~/lynza && ./deploy-app.sh"
